### ISSUE TITLE
Cannot stop transmitting

### ISSUE THREAD

**Issue by robkettridge** [talkkonnect/talkkonnect#3]
I'm running this on a Pi zero W using the work arounds in the talkiepi project. It's up and running and connecting to the channel and receiving audio. However when i start transmitting the user is shown as transmitting and audio is heard but i cannot stop transmitting. I've tried using the GPIO in pi mode (shows in the terminal as button released) or PC mode using the F keys which shows as stop transmitting but nothing stops it transmitting.  The only errors i'm getting are for jack server

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

Any thoughts?

**Comment by robkettridge** [comment]
With regards the audio. Upon further investigation it appears to be fine, but it is echoing constantly in a feedback loop. If i just play a brief bit of sound i get it after a short delay (as expected), but then again, and again, and again, and again, and again, decreasing in volume slightly each time. Takes about 25 repeats before it completely disappears. Also, the longer the program is running, the longer the delay is. After about 1 minute of running the delay is up to about 1 second. If i uncapture the mic input in alsamixer it stops instantaneously. I can quite happily play audio from the mic input to the line output of the usb sound device so that all appears to be working fine.

**Comment by robkettridge** [comment]
With regards the audio, it's fine but running slow, so the longer you leave it running, the more delay there is between the audio going into the line input and coming out of the mumble network. I can't tell if this resets when you stop transmitting and start again as the only way i can stop transmitting is by quitting the programme. Relaunching the program does reset this though.

**Comment by talkkonnect** [comment]
I have personally not tried using the pi zero. Using on raspberry pi 3 and 3B+ and orange pi also on PC works without issue. Are you using GPIO to transmit or you using the keyboard. F8 Starts Transmitting and F9 should stop it. Are you using PUTTY or is it a keyboard connected to raspberry pi. If you are using putty you may need to change the terminal emulation for function keys to work properly. Please do let me know how you are sending commands to talkkonnect.

thank you for the feedback.

**Comment by robkettridge** [comment]
I’ve tried both the gpio and keyboard. Keyboard is directly attached to the pi via a usb hub. (Only one usb on the zero)

It’s an odd one. Is there a way to decrease the cpu usage when sending, lower the quality or something. Just wondering if the high cpu usage whilst transmitting is causing issue. 

I tried Talkiepi before your software and it behaved equally weirdly, although in that case it would fail to start transmitting. The pc software would briefly show it as speaking but then pretty instantly stop. No audio was ever transmitted. 

Thanks for the help

Rob

**Comment by zrdimetc** [comment]
I built talkkonnect on Raspberry Pi Zero and Zero W. No issues on TX. Test PTT GPIO independently of talkkonnect? Try different GPIO? Talkkonnect by default is using 48000 Hz audio sampling. High sampling rate on Raspberry Pi 3b+ results with about 50% CPU usage on TX. Please check post https://github.com/talkkonnect/talkkonnect/issues/2 for information on how to edit audio.go file. You can use 24000, 16000 or 8000 Hz audio sampling rate and the CPU usage will be lower. With 16000 Hz sampling, CPU usage will be around 15-20 % on TX. Talkiepi use 16000 Hz audio by default. You can also use audio.go file from talkiepi (set for 16000 Hz audio).

Edit /home/talkkonnect/gocode/src/github.com/talkkonnect/gumble/gumble/audio.go

Use AudioSampleRate = 16000
AudioDefaultIntervalMS = 60

**Comment by robkettridge** [comment]
Hmm. Changing to those settings causes the output audio to turn to a garbled noise. Changing the sample rate by itself doesn't break anything but it doesn't improve the CPU usage. Changing the default interval to anything other than 10 causes it to garble but does drop the CPU usage though. If i use the Talkiepi file it doesn't work at all. Seems to be down to the different AudioDefaultFrameSize setting. 

None of this fixes the unable to stop transmitting problem though. I'm currently just using the function keys. I have noticed that it doesn't reenable the speaker when i press F9 either

![screen shot 2019-02-06 at 09 45 30](https://user-images.githubusercontent.com/47209273/52333376-0179da00-29f5-11e9-882c-97f438ff1dd7.png)

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to 
replicate your problem and help troubleshoot the issue if I can.
- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as 
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.

Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if 
if you want to use RPi Zero W, with some optimization, it works too.

The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:
1. AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
2. AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
3. AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
4. AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth 
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change <hardware targetboard="rpi"> to <hardware targetboard="pc">
to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change targetboard to 
rpi when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings 
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to 
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.
- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained. Let's try to isolate potential problems with your Zero W build one by one?

Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other 
programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND.  Check your momentary push button? Any other GPIO will work also, as long as they are functional and no conflicts. 

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config under 
<outputdevice> ... </outputdevice> or in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

Let us know if you make your RPi Zero W talkkonnect work?

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to
replicate your problem and help troubleshoot the issue if I can.

- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.
Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if
if you want to use RPi Zero W, with some optimization, it works too.

- The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:

AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change "targetboard" settings to "pc"
to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change "targetboard" to
"rpi" when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.

- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained. 

Let's try to isolate potential problems with your Zero W build one by one?
Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other
programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND. Check your momentary push button? Any other GPIO should work also, as long as there are no conflicts.

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config under
... or in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

Let us know if you make your RPi Zero W talkkonnect work?

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to
replicate your problem and help troubleshoot the issue if I can.

- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- Run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.

Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if
if you want to use RPi Zero W, with some optimization, it works too.

- The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:

AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change "targetboard" settings to "pc" to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change "targetboard" to "rpi" when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.

- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained.
Let's try to isolate potential problems with your Zero W build one by one?
Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other
programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND. Check your momentary push button? Any other GPIO should work also, as long as there are no conflicts.

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config under "<outputdevice>Speaker</outputdevice>"
Change Speaker to your actual sound output device name.
... or in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

I hope this helps. Let us know if you make talkkonnect on your RPi Zero W work?

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to
replicate your problem and help troubleshoot the issue if I can.

- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- Run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.

Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if
if you want to use RPi Zero W, with some optimization, it works too.

- The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:

AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change "targetboard" settings to "pc" to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change "targetboard" to "rpi" when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.

- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained.
Let's try to isolate potential problems with your Zero W build one by one?
Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND. Check your momentary push button? Any other GPIO should work also, as long as there are no conflicts.

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config under "<outputdevice>Speaker</outputdevice>"
Change Speaker to your actual sound output device name.
... or in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

I hope this helps. Let us know if you make your RPi Zero W talkkonnect work?

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to
replicate your problem and help troubleshoot the issue if I can.

- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- Run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.

Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if
if you want to use RPi Zero W, with some optimization, it works too.

- The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:

AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change "targetboard" settings to "pc" to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change "targetboard" to "rpi" when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.

- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained.
Let's try to isolate potential problems with your Zero W build one by one?
Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND. Check your momentary push button? Any other GPIO should work also, as long as there are no conflicts.

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config as "outputdevice".
Change "Speaker" to your actual sound output device name.
... or in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

I hope this helps. Let us know if you make your RPi Zero W talkkonnect work?

**Comment by zrdimetc** [comment]
I just built talkkonect on RPi Zero W, using Suvir's latest github code to try to
replicate your problem and help troubleshoot the issue if I can.

- I used Raspbian Stretch Lite, release date 2018-11-13 (Kernel Version 4.14)
- My USB sound card is CM108, set as
defaults.ctl.card 1
defaults.pcm.card 1
in /usr/share/alsa/alsa.conf
- Verify speaker is working with "speaker-test" and the mic with "arecord -f CD | aplay"
- Run talkiepi workaround patch for removing Neon support
- compiled talkkonnect following instructions in readme.

Result: talkkonnect runs as expected. It runs better on RPi 3B+, 3, or even 2 but if
if you want to use RPi Zero W, with some optimization, it works too.

- The rates in gumble audio.go and how they relate to CPU usage on Raspberry Pi Zero W:

AudioSampleRate = 48000, AudioDefaultIntervalMS = 10 -> CPU usage 80 %
AudioSampleRate = 24000, AudioDefaultIntervalMS = 40 -> CPU usage 40 %
AudioSampleRate = 16000, AudioDefaultIntervalMS = 60 -> CPU usage 34 %
AudioSampleRate = 8000, AudioDefaultIntervalMS = 60-120 -> CPU usage 25-30 %

Probably the best compromise between audio quality, CPU usage and bandwidth
are the settings under 3. (16000 Hz/ 60 ms)

- For the first run of talkkonnect, in talkkonnect.xml
change "targetboard" settings to "pc" to test talkkonnect with keyboard only and isolate any potential GPIO problems. Change "targetboard" to "rpi" when ready to connect GPIO.

- Please note if you use "Putty" some F keys (F1-F4) wont work with default settings
for terminal. Change Putty terminal settings to "X term R6" for all F keys to work.

Suggestions: Try a different server? Another mic, sound card? What Mumble client you use to talk to
talkkonnect? I tried my Zero W client with Mumble for Windows, Plumble and other talkkonnect's
on RPi 2, 3b, 3b+, Orange Pi's. All transmissions were audible at different audio sample rates listed above.

- F8 turns PTT on. F9 release PTT. F11 will stream some radio audio, another F11 stops streaming, etc. Work as expected. I can confirm there are no issues with Suvir's code that can cause issue you explained.
Let's try to isolate potential problems with your Zero W build one by one?
Are you having a stuck PTT only when using GPIO or with F key also? If it's just GPIO, are there any other programs talking to GPIO? Can you try a different BCM pin? Check xml config for any conflict? Test your GPIO? Turn them on and off? Look up for some diagnostic tools like pigpio/ gpiotest or just test them one by one? I tested physical PTT button on RPI Zero W with GPIO 26 (default in xml config). It works. Just short to GND. Check your momentary push button? Any other GPIO should work also, as long as there are no conflicts.

- For muting to work, you need to discover the name of your output sound device (Speaker, Master, Headphone, etc) for amixer to be able to call it - and enter that name in xml config as "outputdevice".
Change "Speaker" to your actual sound output device name.
... or change device name in /home/talkkonnect/gocode/src/github.com/talkkonnect/volume-go/volume-linux.go file.

I hope this helps. Let us know if you make your RPi Zero W talkkonnect work?

**Comment by zrdimetc** [comment]
If i use the Talkiepi file it doesn't work at all. Seems to be down to the different AudioDefaultFrameSize setting.
- You can interchange talkkonnect audio.go with talkiepi audio.go. talkkonnect will 
produce audible sound with talkiepi settings also. When you are changing settings in audio.go 
to your own liking, not all combinations of audio bit rates and timings are supported by Opus. 
Also make sure formulas for frame sizes are correct.  Usually frame size of 960 will always work, 480 most of time, but bigger or smaller frames usually do not work with gumble, talkiepi and talkkonnect to produce audible audio.

**Comment by zrdimetc** [comment]
...If i use the Talkiepi file it doesn't work at all. Seems to be down to the different AudioDefaultFrameSize setting.

- You can interchange talkkonnect audio.go with talkiepi audio.go. talkkonnect will 
produce audible sound with talkiepi settings also. When you are changing settings in audio.go 
to your own liking, not all combinations of audio bit rates and timings are supported by Opus. 
Also make sure formulas for frame sizes are correct. Usually frame size of 960 will always work for all supported audio bit rates, 480 most of time, but bigger or smaller frames usually do not work with gumble, talkiepi and talkkonnect to encode audible audio.

**Comment by zrdimetc** [comment]
->...If i use the Talkiepi file it doesn't work at all. Seems to be down to the different AudioDefaultFrameSize setting.

- You can interchange talkkonnect audio.go with talkiepi audio.go. talkkonnect will
produce audible sound with talkiepi settings also. When you are changing settings in audio.go
to your own liking, not all combinations of audio bit rates and timings are supported by Opus.
Also make sure formulas for frame sizes are correct. Usually frame size of 960 will always work for all supported audio bit rates, 480 most of time, but bigger or smaller frames usually do not work with gumble, talkiepi and talkkonnect to encode audible audio.

**Comment by robkettridge** [comment]
Hmm, leave it with me. I'm going to do a complete reinstall again and see if I have any more luck. I tried the same SD card in an old B+ I had lying around and it did exactly the same so it's obviously something to do with my install.

**Comment by robkettridge** [comment]
Ok.. fresh install from wiped SD card. This is also to a different Mumble server that I've just set up on my home laptop for testing purposes.
Download NOOBS stretch network install, install to SD card. Install raspbian, set network.
Shows as 4.14.79+ #1159
Set sound card 
Test with speaker test and arecord
Install work arounds
Installed talkkonnect following instructions (copied and pasted them all to make sure). 
Built as user talkkonnect
Had the following issues...
- Change the line #PermitRootLogin prohibit-password to PermitRootLogin Yes
   Didn't let me ssh in as root. So logged in as Pi and did su-i to install
- Start talKKonnect binary, cd /home/talkkonnect/bin/talkkonnect
   Directory not found. Program has compiled to /home/talkkonnect/bin/
- ./talkkonnect
   Runs but crashes out saying can't write to /var/log/talkkonnect.log. 
   File does not exist. Cannot create it as user so sudo create it and give owner and group to      talkkonnect user
- Run again, now launches and connects. Never writes anything to the log file though.

Exactly the same issue as before. Only using F-keys. 
F8 gives -
[  info ] 2019/02/07 11:38:00 --                                                      
[  info ] 2019/02/07 11:38:00 F8 pressed TX Mode Requested (Start Transmitting)
[  info ] 2019/02/07 11:38:01 Speaker Muted                                           
[  info ] 2019/02/07 11:38:01 -- 

and shows as talking in other clients and local speaker mutes

F9 gives - 
[  info ] 2019/02/07 11:39:02 --                                                        
[  info ] 2019/02/07 11:39:02 F9 pressed RX Mode Request (Stop Transmitting)
[  info ] 2019/02/07 11:39:02 -- 

Still showing as talking in other clients, local speaker still muted. I can unmute the speaker by pressing F3  - 
[  info ] 2019/02/07 11:39:56 --                                                        
[  info ] 2019/02/07 11:39:56  /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/soundfiles/MuteUnMuteSpeaker.wav
[  info ] 2019/02/07 11:39:57 F3 pressed Mute/Unmute Speaker Requested Now UnMuted
[  info ] 2019/02/07 11:39:57 -- 

Other oddities.. in the XML config file I have set the channel to Root but when it connects it says it can't find the channel Root and have set the ident but it's still showing up as talkkonnect-xxxxxxxxxxxx in the other client. As shown below I have tts set to 'false' in the xml file but pressing F3 to unmute the speaker plays the sound file anyway.

I have set the following to 'false' in the xml file
http auto provisioning 
beacon 
tts 
smtp 
event
alert 
rogerbeep 
chimes 
tx timeout
api listen port is set to server listen port
playchimes
requestgpsposition
sendemail
printvariables set as default
hardware target board set to pc
gps
panicfunction

Not sure any of that helps at all :o/

**Comment by talkkonnect** [comment]
robkettridge,

Let me explain as detailed in the steps below

Obeservation 
1. Change the line #PermitRootLogin prohibit-password to PermitRootLogin Yes
Solution : Should have been yes all lower case letters (this is fixed in the readme file now)
also dont forget to service ssh restart for the config file to be read by ssh and take effect.

2. Start talKKonnect binary, cd /home/talkkonnect/bin/talkkonnect
Solution: cd /home/talkkonnect/bin (this has been fixed in readme file)

3. Nothing written to log file 
Solution: For writing to log both file and screen set the tag in the xml file <logging></logging> (leave it blank -> remove the word screen 
because the word screen forces talkkonnect to log to screen ONLY.

4. Function Keys not working
Solution: Dont know why this is happening with you have tested it here and also on many other devices and its working. I can't recreate the problem here.

5. set the channel to Root but when it connects it says it can't find the channel Root
Solution: To join root channel just leave the tag blank as it will join root channel by default. Only use this tag if you want to join a non-root channel on startup.

6. ident but it's still showing up as talkkonnect-xxxxxxxxxxxx in the other client
Solution: You have to set the username xml tag if you leave it blank talkkonnect will generate automatically talkkonnect-xxxxxxxxxxxx.
The ident xml tag is used for Autoprovisioning and for Identifying the person by name etc for PANIC function only.

7. I have set the following to 'false' in the xml file
Set the below items to FALSE
http auto provisioning, beacon, tts,smtp, alert, tx timeout, requestgpsposition,sendemail, api listen port is set to server listen port,gps,panicfunction 

Set the below items to TRUE
event,rogerbeep,chimes,playchimes

FOR RASPBERRY PI for GPIO to WORK and LCD to WORK set hardware target board to RPI not PC

happy talkkonnecting!!

suvir

**Comment by robkettridge** [comment]
Thanks for those..
1) I guessed this and I had done it with lowercase yes
2) Again, assumed this was a typo. It was more to let you know
3) OK. Not bothered by it not writing to the log, was just wondering if it was indicative of something else
4) The function keys all work. It's just when you press F9 (or release the GPIO button) it doesn't close the stream
5) Ok, will try that. It joins it anyway, was just trying to remove errors
6) I'll check my XML file again
7) I'll set these to true for testing, but eventually i don't want it making any noises whatever you do.

I've got it set to PC rather than RPI as it was suggested for troubleshooting purposes.

I don't suppose you have an image of a working system that i could flash to my SD card just to rule out my installing. Only thing i can think at the moment is it's something to do with the USB sound interface i'm using but i don't see how that's causing the issue. I'm using one of these btw. [https://thepihut.com/products/usb-audio-adapter](https://thepihut.com/products/usb-audio-adapter ). As i said. Works fine with speaker-test and arecord.

Really baffled as to why this isn't working at the moment.... I shall try these things tomorrow and report back. Thank you!

**Comment by robkettridge** [comment]
Right... progress. It turns out the issue is the rogerbeep tag in the XML file. As soon as I set this to 'false' it causes the failing to stop transmitting issue. I can set all the others that you suggested setting to true to false and it still works, as long as rogerbeep is set to true. I've worked round that by just setting the volume of it to 0.

So that works. Just got the audio to fix. Still have the issue that 48000 and 10 works (ish) but is slow and a bit garbled. Setting it to anything else causes just noise. I've attached some audio files as examples....

 
[48000-10.mp3.zip](https://github.com/talkkonnect/talkkonnect/files/2843112/48000-10.mp3.zip)
[16000-60.mp3.zip](https://github.com/talkkonnect/talkkonnect/files/2843113/16000-60.mp3.zip)

Again I tried the talkiepi file and get no audio whatsoever. 

You talk of changing the line AudioDefaultIntervalMS but there is no such line in my audio.go file. There is just the AudioDefaultInterval value which appears to just be the MS value multiplied by time.Millisecond. I have also tried adding the AudioDefaultIntervalMS value and changing the AudioDefaultInterval value to 'AudioDefaultInterval = AudioDefaultIntervalMS * time.Millisecond' which is what it is in the talkiepi file. No change.

**Comment by robkettridge** [comment]
Tonight's update... changed audio interface to a completely different manufacturer / model. Same issue.

**Comment by talkkonnect** [comment]
Rob,
Any CM108 USB sound card should work.  Can you try with Raspbian lite instead of Noobs, never tried Noobs maybe something is missing? Don't know what else to suggest. 
Let us know how you get along.

**Comment by robkettridge** [comment]
Have done a fresh install using Raspbian lite rather than noobs. Didn't have the issue with the SSH this time so followed those instructions as per the guide. Still no joy. I am now getting this error when connecting to the mumble server which I wasn't before..

XDG_RUNTIME_DIR (/run/user/0) is not owned by us (uid 1001), but by uid 0! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

Doesn't seem to be changing anything. I've just ordered a definite CM108 USB card so will report back when that arrives. (my current one doesn't seem to specify what it is (just says USB audio) and the replacement I've borrowed is a 'TI PCM2902 Audio Codec').

**Comment by talkkonnect** [comment]
You should not have pulse audio installed. Talkkonnect works with ALSA and pulse audio is known to give problems. By default pulse audio should not have been installed. Try to remove pulse audio and go with pure alsa. Let me know how it goes.

**Comment by robkettridge** [comment]
I didn't install PulseAudio. If I check the list of installed packages the only thing that shows up vaguely related is libpulse0 which, if I try to uninstall, tries to remove ffmpeg.

I didn't mention last time but I'm still getting jack server errors when starting ./talkkonnect

[  info ] 2019/02/13 15:33:46 Connected to  CSCommsServer   192.168.0.10:64738  on attempt 0
[  info ] 2019/02/13 15:33:46 Welcome message: 
Welcome to this server running Murmur.
Enjoy your stay!
[  info ] 2019/02/13 15:33:47 Channel  Root  has no other participants
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
XDG_RUNTIME_DIR (/run/user/0) is not owned by us (uid 1001), but by uid 0! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

I shall report back once the new USB sound card arrives.

**Comment by talkkonnect** [comment]
You can safely ignore the jack error warnings.

**Comment by robkettridge** [comment]
Right, me again... My CM108 USB card finally turned up. Fresh install, followed examples to the letter, same deal. Also still having that XDG_RUNTIME_DIR error. Thought it might be because I'm running murmur servers on Macs, so tried a PC server. Same deal. I can change the sample rate fine and hear the differences that makes, but any change to the default interval kills the audio as in the example I posted above.

**Comment by talkkonnect** [comment]
Rob,
I really dont know why you are getting the errors. I created a bash script to install talkkonnect to make it easier. We have good success using raspberry pi 3 and 3b+ and I cannot re-create your problem here.

**Comment by talkkonnect** [comment]
Rob,
I managed to recreate your problem here of the TX key not releasing on F9. This only happens when you set rober beep to false. It was a bug in the code. I have fixed it. Please get the version 1.43 which is the latest release as of 27/02/2019 and this problem should be solved. Please do report back your experience and let me know if this problem is solved so I can close this ticket.

**Comment by robkettridge** [comment]
Close the ticket. It was obviously that causing that problem. I'm giving up on this project as I still can't get audio to work properly. I've just tried removing the last constant (which was using a Mac as the receiving client) and that hasn't helped so I'm all out of ideas.

**Comment by zrdimetc** [comment]
I was able to make Talkkonnect run on Raspberry Pi Zero, but this board is just too under powered for encoding Opus 48 kHz sound. It will take almost all CPU resources and operation can be unstable. 
Orange Pi Zero, on the other hand works perfectly and has plenty of CPU power. You can of course use 24, 16, 12 or 8 kHz sound and the program will take less CPU, but there are some incompatibilities between gumble/ talkiepi/ talkkonnect encoded sound and the jitter buffer in Plumble and to a smaller extent official Mumble, which makes the sound encoded with anything else than 48 kHz / 10 ms break up. What client do you use to talk to your RPi Zero talkkonnect? Sound encoded with other sample rates / times works OK between the gumble-like devices (talkkonnect, talkiepi, etc) but lower sample rate / longer times do not work well with Plumble/ Mumble official for the time being. For compatibility, stay with 48k sound and 10 ms for talking to other clients, and for this you need minimum Raspberry Pi 3 or Orange Pi Zero or better boards. Were you able to build talkiepi first? If talkiepi works, talkkonnect will work also. Anyway, try the new code, since Suvir introduced many improvements since March. Did you consider OrangePi Zero? It is as cheap as Raspberry Pi Zero, equally small size, more powerful CPU, but has integrated sound codec with microphone input - no need for USB sound, unlike RPi. Regards.
